name: lydistories
region: lon1

services:
  - name: lydistories
    github:
      repo: balirwaalvin/New-Lydistories
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: bash build.sh
    run_command: cd server && python3 -m gunicorn app:app --bind 0.0.0.0:8080 --workers 2
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs:
      - key: DATABASE_URL
        value: "your-database-url-here"
        type: SECRET
      - key: JWT_SECRET
        value: "lydistories-production-jwt-secret-2026"
        type: SECRET
