name: lydistories
region: lon1

services:
  - name: lydistories
    github:
      repo: balirwaalvin/New-Lydistories
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs:
      - key: DATABASE_URL
        value: "your-database-url-here"
        type: SECRET
      - key: JWT_SECRET
        value: "lydistories-production-jwt-secret-2026"
        type: SECRET
